/**
 * TEST-ONLY deterministic key construction (ADR 0034 section 17).
 *
 * Building a key from a bare scalar or seed asks the engine to derive the public
 * half itself (PKCS8 without a public key, then a JWK export). That works on
 * Bun and was run on workerd and WebKit (section 17), but it is the one engine
 * behavior the protocol does not otherwise depend on, so production never uses
 * it: this file is imported by `internal.ts` and the tests only, never by a
 * production module and never by `index.ts`, and the source guard says so.
 * It exists so a run can be reproduced from a seeded random source and the
 * committed vectors regenerated byte for byte.
 */

import { concat, fromB64u, own, zero } from './bytes.ts';
import { RelayError } from './errors.ts';
import type { EcPair, Rng, Signer } from './primitives.ts';

const hexBytes = (h: string): Uint8Array =>
  Uint8Array.from(h.match(/../g) ?? [], (x) => Number.parseInt(x, 16));
const ED25519_PKCS8 = hexBytes('302e020100300506032b657004220420');
const P256_PKCS8 = hexBytes(
  '3041020100301306072a8648ce3d020106082a8648ce3d030107042730250201010420',
);
/** The P-256 group order. */
const P256_ORDER = hexBytes('ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551');
const P256 = { name: 'ECDH', namedCurve: 'P-256' } as const;

/** An Ed25519 identity from a 32-byte seed. */
export async function signerFromSeed(seed: Uint8Array): Promise<Signer> {
  const pkcs8 = concat(ED25519_PKCS8, seed);
  try {
    const exportable = await crypto.subtle.importKey('pkcs8', pkcs8, 'Ed25519', true, ['sign']);
    const jwk = await crypto.subtle.exportKey('jwk', exportable);
    const key = await crypto.subtle.importKey('pkcs8', pkcs8, 'Ed25519', false, ['sign']);
    return {
      publicKey: fromB64u(jwk.x ?? ''),
      sign: async (message) =>
        new Uint8Array(await crypto.subtle.sign('Ed25519', key, own(message))),
    };
  } finally {
    zero(pkcs8);
  }
}

function validScalar(d: Uint8Array): boolean {
  if (d.length !== 32 || d.every((b) => b === 0)) return false;
  for (let i = 0; i < 32; i++) {
    if ((d[i] ?? 0) !== (P256_ORDER[i] ?? 0)) return (d[i] ?? 0) < (P256_ORDER[i] ?? 0);
  }
  return false;
}

/** Build a P-256 pair from a 32-byte scalar `1 <= d < n`. The scalar is not retained. */
export async function ecPairFromScalar(d: Uint8Array): Promise<EcPair> {
  if (!validScalar(d)) throw new RelayError('MALFORMED');
  const pkcs8 = concat(P256_PKCS8, d);
  try {
    const exportable = await crypto.subtle.importKey('pkcs8', pkcs8, P256, true, ['deriveBits']);
    const jwk = await crypto.subtle.exportKey('jwk', exportable);
    const privateKey = await crypto.subtle.importKey('pkcs8', pkcs8, P256, false, ['deriveBits']);
    return {
      publicKey: concat(Uint8Array.of(4), fromB64u(jwk.x ?? ''), fromB64u(jwk.y ?? '')),
      privateKey,
    };
  } finally {
    zero(pkcs8);
  }
}

/** A pair from the injected source, redrawing a scalar outside `[1, n-1]`. */
export async function ecGenerate(random: Rng): Promise<EcPair> {
  for (;;) {
    const d = random(32);
    try {
      if (validScalar(d)) return await ecPairFromScalar(d);
    } finally {
      zero(d);
    }
  }
}
